"""add confirmed and language fields to check_results

Revision ID: 74368cff2d70
Revises: 1db12ba6a174
Create Date: 2026-06-24 13:23:34.379995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74368cff2d70"
down_revision: str | Sequence[str] | None = "1db12ba6a174"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("confirmed", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "confirmed")
    # ### end Alembic commands ###
