"""create users and history tables

Revision ID: 825e0e04268e
Revises: d87934459547
Create Date: 2026-06-18 18:59:18.386458

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "825e0e04268e"
down_revision: str | Sequence[str] | None = "d87934459547"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
