"""add file_path and detected_language to check_results

Revision ID: 9ab41bf03394
Revises: 74368cff2d70
Create Date: 2026-06-24 14:20:43.180820

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ab41bf03394"
down_revision: str | Sequence[str] | None = "74368cff2d70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("history", "confirmed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history",
        sa.Column("confirmed", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
