"""add confirmed and language fields to check_results

Revision ID: af1868377487
Revises: 825e0e04268e
Create Date: 2026-06-23 13:19:25.800732

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af1868377487"
down_revision: str | Sequence[str] | None = "825e0e04268e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("history")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("github_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("avatar_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_table(
        "history",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("repo_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("task_description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("planner_response", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("coder_response", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("history_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("history_pkey")),
    )
    # ### end Alembic commands ###
