"""create users and history tables

Revision ID: d87934459547
Revises:
Create Date: 2026-06-18 18:47:44.233890

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d87934459547"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
