name: CI/CD pipeline
on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: install dependencies
        working-directory: frontend
        run: npm install
      
      - name: build 
        working-directory: frontend
        env: 
            VITE_API_URL: ${{ secrets.VITE_API_URL}}
        run: npm run build
  

  build-backend:
     name: build backend
     runs-on: ubuntu-latest
     steps:
      - name: get code
        uses: actions/checkout@v4
      
      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.14
      
      - name: install dependencies
        working-directory: backend
        run: uv sync

      - name: run tests
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL}}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY}}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY}}
          CODER_MODEL: ${{ secrets.CODER_MODEL}}
          PLANNER_MODEL: ${{ secrets.PLANNER_MODEL}}
        run: uv run pytest  